import numpy as np
from bokeh.models import FixedTicker


class CBar:
    def __init__(self, control_width):
        self.control_width = control_width

        self.full_dict = {
            'Cover': {'cmap': 'brg',
                      'clim': (0, 1.0),
                      'barlim': (0.0, 1.0),
                      'colorbar_opts': {'height': 20,
                                        'width': int(self.control_width*0.95),
                                    'background_fill_alpha': 0.0,
                                    'ticker': FixedTicker(ticks=[0.05, 0.50, 0.95]),
                                    'major_label_overrides': {0.05: 'Bare', 0.50: 'Dry', 0.95: 'Green'}}},
            'Bare ground change': {'cmap': 'RdBu_r',
                    'clim': (-0.25, 0.25),
                    'barlim': (-0.25, 0.25),
                    'colorbar_opts': {'height': 20,
                                      'width': int(self.control_width*0.95),
                                      'background_fill_alpha': 0.0,
                                      'ticker': FixedTicker(ticks=np.arange(-0.25, 0.30, 0.05)),
                                      'major_label_overrides': {-0.25: '< -0.25', 0.25: '0.25+'}}},
            'Greenness (NDVI)': {'cmap': 'viridis',
                                 'clim': (0.05, 0.5),
                                 'barlim': (0.0, 0.55),
                                 'colorbar_opts': {'height': 20,
                                                   'width': int(self.control_width*0.95),
                                                   'background_fill_alpha': 0.0,
                                                   'ticker': FixedTicker(ticks=[0.05, 0.175, 0.325, 0.475]),
                                                   'major_label_overrides': {0.05: 'V. Low', 0.175: 'Low', 0.325: 'Mod', 0.475: 'High'}}},
            'Relative greenness': {'cmap': 'RdYlGn',
                              'clim': (50, 150),
                              'barlim': (40, 160),
                              'colorbar_opts': {'height': 20,
                                                'width': int(self.control_width*0.95),
                                                'background_fill_alpha': 0.0,
                                                'ticker': FixedTicker(ticks=[55, 75, 100, 125, 145]),
                                                'major_label_overrides': {55: '50%', 75: '75%', 100: 'Avg.', 125: '125%', 145: '145%'}}},
            'Greenness change': {'cmap': 'RdBu',
                    'clim': (-0.15, 0.15),
                    'barlim': (-0.15, 0.15),
                    'colorbar_opts': {'height': 20,
                                      'width': int(self.control_width*0.95),
                                      'background_fill_alpha': 0.0,
                                      'ticker': FixedTicker(ticks=np.arange(-0.15, 0.20, 0.05)),
                                      'major_label_overrides': {-0.15: '< -0.15', 0.15: '0.15+'}}},
            'Biomass': {'cmap': 'inferno',
                        'clim': (100, 2000),
                        'barlim': (0, 2500),
                        'colorbar_opts': {'height': 20,
                                          'width': int(self.control_width*0.95),
                                          'background_fill_alpha': 0.0,
                                          'ticker': FixedTicker(ticks=np.arange(250, 2500, 250)),
                                          'major_label_overrides': {2000: '2000+'}}},
            'Biomass change': {'cmap': 'RdBu',
                    'clim': (-200, 200),
                    'barlim': (-200, 200),
                    'colorbar_opts': {'height': 20,
                                      'width': int(self.control_width*0.95),
                                      'background_fill_alpha': 0.0,
                                      'ticker': FixedTicker(ticks=np.arange(-200, 250, 50)),
                                      'major_label_overrides': {-200: '< -200', 200: '200+'}}},
            'Biomass threshold': {'cmap': 'Spectral_r',                         
                                  'clim': (0.0, 1.0),
                                  'barlim': (0.0, 1.0),
                                  'colorbar_opts': {'height': 20,                                              
                                                    'width': int(self.control_width*0.95),
                                                    'background_fill_alpha': 0.0,
                                                    'ticker': FixedTicker(ticks=np.round(np.arange(0.1, 1.1, 0.2), 1)),
                                                    'major_label_overrides': {0.1: 'Unlikely', 0.3: '', 0.5: 'Possible', 0.7: '', 0.9: 'Likely'}}},
            'Relative biomass': {'cmap': 'RdYlGn',
                                 'clim': (50, 150),
                                 'barlim': (40, 160),
                                 'colorbar_opts': {'height': 20,
                                                   'width': int(self.control_width*0.95),
                                                   'background_fill_alpha': 0.0,
                                                   'ticker': FixedTicker(ticks=[55, 75, 100, 125, 145]),
                                                   'major_label_overrides': {55: '50%', 75: '75%', 100: 'Avg.', 125: '125%', 145: '145%'}}},
            'Crude protein': {'cmap': 'viridis',
                              'clim': (6, 12),
                              'barlim': (5.5, 13),
                              'colorbar_opts': {'height': 20,
                                                'width': int(self.control_width*0.95),
                                                'background_fill_alpha': 0.0,
                                                'ticker': FixedTicker(ticks=np.arange(6, 13, 1)),
                                                'major_label_overrides': {6: '< 6', 12: '12+'}}},
            'Crude protein change': {'cmap': 'RdBu',
                    'clim': (-3, 3),
                    'barlim': (-3, 3),
                    'colorbar_opts': {'height': 20,
                                      'width': int(self.control_width*0.95),
                                      'background_fill_alpha': 0.0,
                                      'ticker': FixedTicker(ticks=np.arange(-3, 3.5, 0.5)),
                                      'major_label_overrides': {-3: '< -3', 3: '3+'}}},
        }

    def get(self, name):
        return self.full_dict[name]